# Generated by Django 3.2.5 on 2021-07-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(blank=True, max_length=200, null=True)),
                ('Overview', models.BooleanField(default=False)),
                ('AddProduct', models.BooleanField(default=False)),
                ('EditProduct', models.BooleanField(default=False)),
                ('ManageRoles', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200, unique=True)),
                ('Password', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('Role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EcommerceBase.privileges')),
            ],
        ),
    ]
