# Generated by Django 3.2.5 on 2021-07-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceBase', '0005_auto_20210701_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inStock',
            field=models.DecimalField(decimal_places=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.DecimalField(decimal_places=0, max_digits=7, null=True),
        ),
    ]
